const AndhraPradeshDist = [
  "Anantapur",
  "Chittoor",
  "East Godavari",
  "Guntur",
  "Krishna",
  "Kurnool",
  "Prakasam",
  "Srikakulam",
  "Nellore",
  "Visakhapatnam",
  "Vizianagaram",
  "WestGodavari",
  "Kadapa",
];
const TelanganaDist = [
  "Adilabad",
  "Kothagudem",
  "Hyderabad",
  "Jagtial",
  "Jangaon",
  "Jayashankar Bhupalpally",
  "Jogulamba Gadwal",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Kumuram Bheem",
  "Mahabubabad",
  "Mahabubnagar",
  "Mancherial",
  "Medak",
  "Medchal Malkajgiri",
  "Mulugu",
  "Nagarkurnool",
  "Nalgonda",
  "Nirmal",
  "Nizamabad",
  "Peddapalli",
  "Rajanna Sircilla",
  "Rangareddy",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Wanaparthy",
  "Warangal",
  "YadadriBhuvanagiri",
];

export const indianStates = {
  AndhraPradesh: [...AndhraPradeshDist],
  Assam: [],
  ArunachalPradesh: [],
  Bihar: [],
  Goa: [],
  Gujarat: [],
  JammuKashmir: [],
  Jharkhand: [],
  WestBengal: [],
  Karnataka: [],
  Kerala: [],
  MadhyaPradesh: [],
  Maharashtra: [],
  Manipur: [],
  Meghalaya: [],
  Mizoram: [],
  Nagaland: [],
  Orissa: [],
  Punjab: [],
  Rajasthan: [],
  Sikkim: [],
  TamilNadu: [],
  Tripura: [],
  Telangana: [...TelanganaDist],
  Uttaranchal: [],
  UttarPradesh: [],
  Haryana: [],
  HimachalPradesh: [],
  Chhattisgarh: [],
};
